name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Authenticate IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::819628840011:role/test-role-for-github'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="os_type=windowsserver2022" -var="instance_name=test-ec2-tf" -var="instance_type=t3.micro"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="os_type=windowsserver2022" -var="instance_name=test-ec2-tf" -var="instance_type=t3.micro"